server:
  port: 9870
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

springdoc: # documentation: https://springdoc.org/
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: '/swagger-ui.html'
  pathsToMatch: '/simple-server/api/**'
  packagesToScan: 'com.github.truongbb.simplespringserver.controller'
  default-consumes-media-type: 'application/json'

spring:
  application:
    name: 'simple-spring-server'

  banner:
    charset: UTF-8

  data:
    rest:
      base-path: 'simple-server/api'
