server:
  port: 9870
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  application:
    name: 'simple-spring-server'

  banner:
    charset: UTF-8

  data:
    rest:
      base-path: 'simple-server/api'

